version: 2
jobs:
  unit-tests:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - run:
          name: Install libsecp256k1
          command: brew tap cuber/homebrew-libsecp256k1 && brew install libsecp256k1
      - run: swift test --filter SteemTests
  integration-tests:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - run:
          name: Install libsecp256k1
          command: brew tap cuber/homebrew-libsecp256k1 && brew install libsecp256k1
      - run: swift test --filter SteemIntegrationTests
  linux-tests:
    docker:
      - image: swift:4
    steps:
      - checkout
      - run: swift test
workflows:
  version: 2
  build:
    jobs:
      - unit-tests
      - integration-tests
      - linux-tests
