version: 2
show_swift_version: &show_swift_version
  run:
    name: Swift version
    command: swift -version
jobs:
  unit-tests:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - <<: *show_swift_version
      - run:
          name: Run unit tests
          command: swift test --filter SteemTests
  integration-tests:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - <<: *show_swift_version
      - run:
          name: Run integration tests
          command: swift test --filter SteemIntegrationTests
  linux-tests:
    docker:
      - image: swift:4
    steps:
      - checkout
      - <<: *show_swift_version
      - run:
          name: Run tests
          command: swift test
workflows:
  version: 2
  build:
    jobs:
      - unit-tests
      - integration-tests
      - linux-tests
