version: 2
jobs:
  unit-tests:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - run:
          name: Install libsecp256k1
          command: brew tap cuber/homebrew-libsecp256k1 && brew install libsecp256k1
      - run: swift test --filter SteemTests
  integration-tests:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - run:
          name: Install libsecp256k1
          command: brew tap cuber/homebrew-libsecp256k1 && brew install libsecp256k1
      - run: swift test --filter SteemIntegrationTests
  linux-tests:
    docker:
      - image: swift:4
    steps:
      - checkout
      - run:
          name: Get latest libsecp256k1 version
          command: |
            VERSION=`git ls-remote https://github.com/bitcoin-core/secp256k1.git | grep "HEAD$" | cut -f1`
            echo $VERSION | tee .libsecp256k1_head
      - restore_cache:
          keys:
            - libsecp256k1-{{ checksum ".libsecp256k1_head" }}
      - run:
          name: Install libsecp256k1
          command: |
            test -f /usr/local/include/secp256k1.h && exit
            git clone https://github.com/bitcoin-core/secp256k1.git && cd secp256k1
            apt-get update && apt-get install -y autoconf libtool
            ./autogen.sh && ./configure --enable-module-recovery
            make install
      - save_cache:
          key: libsecp256k1-{{ checksum ".libsecp256k1_head" }}
          when: always
          paths:
            - /usr/local/lib
            - /usr/local/include
      - run:
          name: Run tests
          command: ldconfig && swift test
workflows:
  version: 2
  build:
    jobs:
      - unit-tests
      - integration-tests
      - linux-tests
